### PR TITLE
Update nlohmann/json library (fixes #284)

### LINKED ISSUE #284: ModernJson is outdated
The ModernJson version we are using is Version 2.0.5, dated 2016.

### PR DESCRIPTION
**Pull request by tquatmann**
I re-applied the [changes](https://github.com/moves-rwth/storm/commit/632c9c2e1e7cdfe36aba1287788021261671164f#diff-e1d25a1c865ce280fc884d097b0030464e4f3e58d24acc4baa0981d3d69a9671) made to the old json version concerning RationalNumber support.

My changes to the main nlohmann/json release can be seen [here](https://github.com/tquatmann/json/commit/48ebe445314e798af208851374fb9508a45d199a)

I briefly checked for obvious performance regressions, which does not seem to be the case.
Here some data, where I used storm-conv to parse and then export a ~38 MB JANI file from QVBS:

current main:
```console
Command line arguments: --jani oscillators.8-10-0.1-1.jani --tojani test1 -jprop --compactjson
Current working directory: /Users/tim/git/qcomp/benchmarks/dtmc/oscillators

Parsing JANI input ...  done. (2.175s seconds).
Performing transformations on JANI model ...  done. (0.201s seconds).
Exporting JANI model ... Stored to file 'test1' done. (1.268s seconds).
```

This branch:
```console
Command line arguments: --jani oscillators.8-10-0.1-1.jani --tojani test1 -jprop --compactjson
Current working directory: /Users/tim/git/qcomp/benchmarks/dtmc/oscillators

Parsing JANI input ...  done. (2.199s seconds).
Performing transformations on JANI model ...  done. (0.200s seconds).
Exporting JANI model ... Stored to file 'test1' done. (1.081s seconds).
?master ~/git/qcomp/benchmarks/dtmc/oscillators> 
```

### CODE REVIEW

**Comment by tquatmann** [comment]
I still need to add some documentation [here](https://github.com/moves-rwth/storm/blob/master/doc/update_resources.md) before merging this.

**Comment by sjunges** [comment]
You are a true hero :-)

**Comment by sjunges** [comment]
Is there any reason why we did not specialize std::is_scalar_v in the changes within modernjson? That would have saved quite some lines in the diff?

**Comment by sjunges** [comment]
Your changes in this PR LGTM

**Comment by tquatmann** [comment]
specialising is_scalar (and similar traits) would be great, but (quoting [cppreference](https://en.cppreference.com/w/cpp/types/is_scalar) ):

> The behavior of a program that adds specializations for std::is_scalar or std::is_scalar_v is undefined.

**Comment by tquatmann** [comment]
I made the json export a bit more robust (in case a huge `storm::RationalNumber` like `1E5000` might be converted to something like `nan` and/or `inf`.

I also added the promised documentation. From my side, this is ready to be merged :)

**Comment by sjunges** [comment]
LGTM!

**Comment by marisgg** [comment]
The Stormpy master fork fails (https://github.com/randriu/stormpy/actions/runs/6945132931/job/18893799741) on the latest version of Storm CI, possibly due to this PR. The error is inside `CMakeFiles/utility.dir/src/utility/json.cpp`.

I'm assuming this very recently started Stormpy build (https://github.com/moves-rwth/stormpy/actions/runs/6945494052/job/18894977397) will fail because of this.

**Comment by sjunges** [comment]
Looking at this, the problem is here: https://github.com/randriu/stormpy/blob/master/src/utility/json.cpp but I dont know where exactly. Maybe @tquatmann sees it?

**Pull request merged**
