### PR TITLE
Code formatting for storm-dft

### PR DESCRIPTION
**Pull request by volkm**
Enable automatic code formatting for `storm-dft`, `storm-dft-cli` and `test/storm-dft`.

### CODE REVIEW

**Comment by sjunges** [comment]
LGTM

**Comment by tquatmann** [comment]
For the historians among us: I recommend to add the code-formatting commit hash to the `.git-blame-ignore-revs` file.

If you use the github workflow to apply the actual code formatting, it will add the commit hash automatically and also uses a dedicated committer name. Maybe that's preferable :)

**Comment by sjunges** [comment]
> For the historians among us: I recommend to add the code-formatting commit hash to the `.git-blame-ignore-revs` file.
> 
> If you use the github workflow to apply the actual code formatting, it will add the commit hash automatically and also uses a dedicated committer name. Maybe that's preferable :)

Ah that is how that works! Great!

**Comment by volkm** [comment]
So the preferred way would be to only remove the storm-dft directories from `.clang-format-ignore` and let the github workflow take care of the rest?

**Pull request closed without merging**
