### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by sjunges**

### CODE REVIEW

**Review by volkm — APPROVED** [review]
Good catches w.r.t. `pragma` and thanks for disabling the Eigen warnings.

**Comment by sjunges** [comment]
I saw that I introduced a new warning. Will delay merging this until I have time.

**Comment by sjunges** [comment]
The problem is that old gcc version do not support -Wdeprecated-enum-enum-conversion while newers throw a warning. How shall i handle this? Accept the warning about pragmas in old gccs? Maybe we can detect GCC versions and disable warnings about unknown pragmas on old gccs? (but i really would love to focus on new gcc versions)

**Comment by sjunges** [comment]
@tquatmann  decided that introducing the warning on Ubuntu 20.04 and Debian 11 is ok for now

**Pull request merged**
