### PR TITLE
remove cuda 

### PR DESCRIPTION
**Pull request by sjunges**
As discussed, the cuda code base is horrribly outdated and not maintained, therefore, we remove it

### CODE REVIEW

**Review by volkm — APPROVED** [review]

**Comment by sjunges** [comment]
searching for cuda in the source and resource folder was appearantly not a good strategy. Let me remove that folder before merging

**Comment by sjunges** [comment]
I would prefer to make a seperate PR for the changelog as all the different PRs will conflict if they all touch the changelog ... i have not figured out a good way of doing this

**Comment by tquatmann** [comment]
LGTM

**Comment by volkm** [comment]
Thanks for removing the cuda folder. Looks good now.

**Pull request merged**
