### PR TITLE
move gamebased-ar to own lib

### PR DESCRIPTION
**Pull request by sjunges**
Fixes https://github.com/moves-rwth/storm/issues/338
Also ensures compilation with MathSat again, see also https://github.com/moves-rwth/storm/issues/433

The 105 files touched are not soo bad ;-)

I noticed that there are a lot of thin check result classes that we may want to move back or replace at some point. No need to do that now.

### CODE REVIEW

**Comment by volkm** [comment]
I would suggest to also add a namespace `storm::gamebased` or similar.

**Comment by volkm** [comment]
I also saw some changes related to includes in `storm-pars` etc which seem not related to the changes in this PR. Are they needed to ensure compilation?

**Comment by sjunges** [comment]
Regarding the discussion in #435: I cannot do the namespace refactoring today/tomorrow. We may want to consider merging this and i can handle an issue on renaming the namespace later. Or you'll have to wait a bit :-)

**Comment by volkm** [comment]
I am fine with merging this PR and changing the namespace later on.
I guess the changes in storm-pars are needed here because some includes are missing after moving the files?

**Comment by tquatmann** [comment]
I'm also fine with merging this now and change the namespace later.
BTW, my vote is for `storm::abstraction` or `storm::gbar` or `storm::gamebased_ar" or something, since `gamebased` alone is a bit too generic imo

**Pull request merged**
