### PR TITLE
Removed forcing old version of optional (Fixes #80 Fixes #232)

### LINKED ISSUE #80: Boost: Old version of optional
The [CMakeLists.txt](https://github.com/moves-rwth/storm/blob/1343ae5c19e731573568dd6a3cfcbd06b722f9b5/CMakeLists.txt#L236) still contains this:
```
# TODO: remove forcing the old version of optional as soon as the related Spirit bug is fixed:
# https://svn.boost.org/trac/boost/ticket/12349
# Fix thanks to: https://github.com/freeorion/freeorion/issues/777
add_definitions(-DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL)
```

I have looked this up and it seems that the issue is fixed since boost 1.67.0 (However, I haven't tested this, yet).
If we drop the fix, we no longer support Debian 9 (Boost 1.62.0) and Ubuntu 18.04 (Boost 1.65.1) which might still be in use somewhere.

I would suggest detecting the boost version and enable/disable the fix automatically.

### LINKED ISSUE #232: Version issue with `boost` (workaround)
**Short Bug Description**: On systems where a version of `boost` newer than 1.78.0 is installed but 1.78 is not installed, STORM does not properly link, even though an executable is created. On runtime, an error is emitted:
```
./storm: error while loading shared libraries: libboost_filesystem.so.1.78.0: cannot open shared object file: No such file or directory
```
**More Information**: It appears in CMakeLists.txt:269-272 the following code forces an old version of `boost::optional` to be used:
```cmake
# TODO: remove forcing the old version of optional as soon as the related Spirit bug is fixed:
# https://svn.boost.org/trac/boost/ticket/12349
# Fix thanks to: https://github.com/freeorion/freeorion/issues/777
add_definitions(-DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL)
```
However, I have used STORM (mostly through our project, STAMINA, which is built on top of STORM), using Boost: 1.79 with no issue. I would like to make it clear that **THIS HAS JUST BEEN MY EXPERIENCE. BOOST 1.79 MAY BREAK SOMETHING IN STORM FOR A FEATURE I DON'T GENERALLY USE**. Therefore I have used the following workaround on my system:

**Easy workaround**: Create symlinks that link libboost_*.so.1.* to libboost_*.so.1.78. For my system, which has 1.79 on it, the following script does it for me:

```bash
sudo ln -T /usr/lib/libboost_filesystem.so.1.79.0 /usr/lib/libboost_filesystem.so.1.78.0
sudo ln -T /usr/lib/libboost_system.so.1.79.0 /usr/lib/libboost_system.so.1.78.0
sudo ln -T /usr/lib/libboost_program_options.so.1.79.0 /usr/lib/libboost_program_options.so.1.78.0
sudo ln -T /usr/lib/libboost_regex.so.1.79.0 /usr/lib/libboost_regex.so.1.78.0
sudo ln -T /usr/lib/libboost_unit_test_framework.so.1.79.0 /usr/lib/libboost_unit_test_framework.so.1.78.0
```

**More Permanent Solution**: If the Spirit bug no longer exists in boost, or if it doesn't affect STORM, you could simply remove lines 269-272 in `CMakeLists.txt`, but this needs to be tested before done. I am posting this workaround in this bug report because it worked for me so others can try it and see if it works for them. Note that Boost 1.78 is not available in my `pacman` repositories.

**System Information**:
System type: Linux (Manjaro)
Kernel: 5.18.6-1-MANJARO \#1 SMP PREEMPT_DYNAMIC
Architecture type: x86_64 GNU/Linux
DE: Plasma 5.24.5 
Shell: zsh 5.9 (x86_64-pc-linux-gnu)
Boost Version: 1.79
`git` branch of STORM used: HEAD -> master (hash: a491f13e738ba4491fc26acca351e20bbe9506fc)

### PR DESCRIPTION
**Pull request by tquatmann**
This PR removes a workaround for an old bug in boost::spirit.

This fixes issue #80 and issue #232
According to  #80, this PR breaks support for ubuntu 18-04 (which is fine in my opinion)

### CODE REVIEW

**Comment by volkm** [comment]
Looks good.
Maybe we should explicitly set a minimal Boost version or at least issue a warning if the Boost version is too old.

**Comment by volkm** [comment]
From the tests it seems that Ubuntu 18.04 also works with this change. Maybe PR #234 is not necessary?

**Comment by tquatmann** [comment]
Indeed, we should increase the minimal required  boost version. `resources/3rdparty/CMakeLists.txt` currently requires at least Boost 1.61.0 . 

Yes, as it seems to work with 18-04, I'll discard PR #234 and set the minimum version to 1.65.1

**Comment by volkm** [comment]
Thanks for integrating the suggestion.

**Pull request merged**
